### ISSUE TITLE
Migrations not running

### ISSUE THREAD

**Issue by michaelminter** [solidusio-contrib/solidus_static_content#3]
Calling the generator updates the frontend css file but doesn't run migrations. Manually trying to run the railties and migrate commands don't do anything either. Any ideas?

**Comment by michaelminter** [comment]
Running rake railties:install:migrations without the FROM=solidus_static_content worked :)

**Comment by nbrookie** [comment]
I have ran into the same issue. Using rails 5.0.0.1 and ruby 2.3.1.

Running `rails g solidus_static_content:install` appears to have only copied a line into the `vendor/assets/stylesheets/spree/frontend/all.css` stylesheet. However, no migrations were copied over and ran 😢  

Doing `rake railties:install:migrations FROM=spree_static_content` and `rake db:migrate` manually  solved the issue. Could not seem to figure out the cause though.
