### ISSUE TITLE
DB Migration not working

### ISSUE THREAD

**Issue by dantio** [solidusio-contrib/solidus_static_content#4]
`bundle exec rails g solidus_static_content:install` should copy migration files, but it's not working for my project. (Rails 5.0, Solidus 2.0)

After I run ` bundle exec rails railties:install:migrations`, all migration files are copied and with `bundle exec rails db:migrate` I'm able to use the static pages.

**Comment by mbreedlove** [comment]
I had the same issue. `railties:install:migrations` worked for me also.

**Comment by MrRezaque** [comment]
Had issues with migrations in rails 5.0.2, it won't work for `railties:install:migrations FROM="solidus_static_content"`, but works with `railties:install:migrations SCOPE="solidus_static_content"`

**Comment by kendocode** [comment]
Same issue (Rails 5.0.4, Solidus v2.2); initial fix worked for me as well. Thanks @DaniilTomilow!

**Comment by asecondwill** [comment]
+1

**Comment by sbezugliy** [comment]
The same. Solved using console and copying migrations to the projects root.

**Comment by nxtbz** [comment]
+1
