### ISSUE TITLE
undefined method `glob'

### ISSUE THREAD

**Issue by pailoro** [solidusio-contrib/solidus_static_content#57]
Hi, 

I did the instalation of the gem, but when I run 

`bundle exec rails generate solidus_static_content:install`

I get the error:

`/bundler/gems/solidus_static_content-8fea401c2818/lib/spree_static_content/engine.rb:22:in activate_overrides: undefined method glob for #<Pathname:0x00000000096fa028> (NoMethodError)`

someone already got this error before?

Thanks!

**Comment by wayferer** [comment]
I just tried it out and on the master branch readme is suggests putting the following into the Gemfile:

```
gem 'solidus_static_content'
```

Doing so gave me issues with running bundle install. I poked around the other branches and found one where the readme mentions doing it with the following:

```
gem 'solidus_static_content', github: 'solidusio-contrib/solidus_static_content'
```

I was able to get it running no issues after that.
