### ISSUE TITLE
Integration with headless CMS

### ISSUE THREAD

**Issue by aldesantis** [solidusio-contrib/solidus_static_content#61]
It would be really great if solidus_static_content also allowed you to pull content from a headless CMS such as [Contentful](https://www.contentful.com/) or [Prismic](https://prismic.io/), e.g. by leveraging [Renderful](https://github.com/nebulab/renderful).

I imagine that we could implement an adapter-based approach such as:

```ruby
SolidusStaticContent.configure do |config|
  # Design pages in the Solidus backend (current approach).
  config.adapter = SolidusStaticContent::Adapter::Static.new

  # Retrieve pages through Renderful.
  config.adapter = SolidusStaticContent::Adapter::Renderful.new(client: renderful)
end
```

Then, in the backend UI, admins would be able to either:

1. enter the page's content through the WYSIWYG editor, if they are using the `Static` adapter, or
2. choose a content entry from the ones available in the headless CMS, if they are using the `Renderful` provider.

This would give Solidus store owners full flexibility as to where and how they want to store and manage their content.

**Comment by elia** [comment]
I ❤️ this, probably I would also like to allow picking the provider for each route mount or even for each page. I'll develop a full RFC for how it should work so we can discuss that in detail 👍 .

**Comment by elia** [comment]
The work on this has started, progress can be followed on https://github.com/nebulab/solidus_content/projects/1.
