### ISSUE TITLE
Prepare Solidus Static Content for Solidus 3.0

### ISSUE THREAD

**Issue by kennyadsl** [solidusio-contrib/solidus_static_content#75]
Update this extension so that it works with Solidus 3.0 by making sure the specs pass.

**Comment by jarednorman** [comment]
I got this one.

**Comment by jarednorman** [comment]
I opened #76 to address an issue running the specs against recent versions of Chrome when headless, but this extension doesn't trigger any deprecations on v2.11.

**Comment by seand7565** [comment]
@jarednorman The PR above has been merged, is this issue closable now?

**Comment by jarednorman** [comment]
It is, so long as we're closing these issues without yet having updated the Solidus dependency in the gemspec. I wasn't sure what the plan was there.

**Comment by kennyadsl** [comment]
Yes, I think we should also update the dependency in the gemspec when needed.
