### ISSUE TITLE
It doesnt support translations (globalize)

### ISSUE THREAD

**Issue by recyclablestudios** [solidusio-contrib/solidus_static_content#8]
It doesn allow to make translations

**Comment by elia** [comment]
_Although I'm aware it's two and a half years later, I'll write a reply for other people potentially interested in this_

For now this is beyond the scope of this extension, but this can be reconsidered if there's enough demand. 

---

In my opinion, a more complete CMS solution would be a better route compared to adding features to this extension.

Meanwhile I'd suggest trying with multiple pages (one for each language) and use some consistent slug naming (like `/en-about`, `/it-about`, etc.), that should help to some extent.
