### ISSUE TITLE
admin menu item 'Pages' still appears after logout

### ISSUE THREAD

**Issue by salsysd** [solidusio-contrib/solidus_static_content#9]
I'm stilll getting the 'Pages' menu item after I logout...

<img width="691" alt="user_sessions" src="https://user-images.githubusercontent.com/105071/29266418-edcb4cda-80a1-11e7-8bc0-d6b01c480cc1.png">

**Whats the issue here?**

**Comment by tvdeyen** [comment]
There is no check for the user having permission to see this tab or not. 

This is solved as part of #6  but this PR is failing and does more then only fixing this. 

A PR extracting the fix (removing the deface override and using the menu configuration instead) would be great.

**Comment by elia** [comment]
Fixed by #45
